languageCode: en-us
theme: hugo-docs
uglyURLs: false
refLinksErrorLevel: ERROR
baseURL: https://docs.livingdocs.io/
title: Livingdocs Documentation
enableGitInfo: true
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 2

  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 1

minify:
  tdewolff:
    html:
      keepWhitespace: false

services:
  googleAnalytics:
    id: GTM-K6QTH5K

imaging:
  quality: 75

disableKinds:
  - taxonomy
  - term

outputFormats:
  SearchIndex:
    baseName: search
    mediaType: application/json

outputs:
  home: [HTML, RSS, SearchIndex]

params:
  branch: main
